mode: deployment

replicaCount: 1

image:
  repository: otel/opentelemetry-collector-k8s

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

    jaeger: null
    zipkin: null
    prometheus: null

  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

    batch:
      timeout: 5s

    k8s_attributes:
      auth_type: serviceAccount
      passthrough: false

  exporters:
    debug: null

    otlp/tempo:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true

  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133

  service:
    extensions:
      - health_check

    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - k8sattributes
          - batch
        exporters:
          - otlp/tempo

      metrics: null
      logs: null

presets:
  kubernetesAttributes:
    enabled: true

ports:
  otlp:
    enabled: true

  otlp-http:
    enabled: true

  jaeger-compact:
    enabled: false

  jaeger-thrift:
    enabled: false

  jaeger-grpc:
    enabled: false

  zipkin:
    enabled: false

  metrics:
    enabled: true

service:
  type: ClusterIP

serviceMonitor:
  enabled: true
