apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: inari
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    vault:
      server: http://vault.win-ts.int:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-inari
          serviceAccountRef:
            name: eso-vault-auth
            audiences:
              - vault
