apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inari-external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/win-ts/homelab-cluster.git
    targetRevision: main
    path: k8s/external-secrets/inari
  destination:
    server: https://kubernetes.default.svc
    namespace: inari
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - SkipDryRunOnMissingResource=true
